### ISSUE TITLE
gitbook 生成失败

### ISSUE THREAD

**Issue by lujg** [rootsongjc/kubernetes-handbook#221]
1. makefile中关于 mobi输出的文件格式出错
2. 利用*gitbook*生成有关文件时出错
* 使用平台：Windows10
* nodeJS版本：v8.11.2 ， npm版本：5.6.0
* 现象：
   * Error: Cannot find module 'prismjs/components/prism-dockerfile.js' 
  * Template render error: (kubernetes-handbook\practice\manage-compute-resources-container.md) [Line 196, Column 94] unexpected token: .

**Comment by rootsongjc** [comment]
`Error: Cannot find module 'prismjs/components/prism-dockerfile.js`这个错误是因为书中有的地方使用的是 `Dockerfile` 代码块，而 prism 中没有 Dockerfile 相应的代码高亮配置。
另外我没有在 Windows 上测试过，在 Mac 上生成 PDF 是没有问题的，生成 mobi 我再试一下。

**Comment by sadlar** [comment]
mac 上出现同样的问题 
```
warn: "options" property is deprecated, use config.get(key) instead
warn: "options.generator" property is deprecated, use "output.name" instead
Failed to load prism syntax: dockerfile
{ Error: Cannot find module 'prismjs/components/prism-dockerfile.js' 
```

**Comment by sadlar** [comment]
```
warn: "options" property is deprecated, use config.get(key) instead
warn: "options.generator" property is deprecated, use "output.name" instead
Failed to load prism syntax: dockerfile
{ Error: Cannot find module 'prismjs/components/prism-dockerfile.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireSyntax (/Users/sadlar/Documents/kubernetes-handbook/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/Users/sadlar/Documents/kubernetes-handbook/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/Users/sadlar/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /Users/sadlar/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /Users/sadlar/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /Users/sadlar/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
```

**Comment by sadlar** [comment]
mac 上的报错：
```
warn: "options" property is deprecated, use config.get(key) instead
warn: "options.generator" property is deprecated, use "output.name" instead
Failed to load prism syntax: dockerfile
{ Error: Cannot find module 'prismjs/components/prism-dockerfile.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at requireSyntax (/Users/sadlar/Documents/kubernetes-handbook/node_modules/gitbook-plugin-prism/index.js:31:3)
    at Object.code (/Users/sadlar/Documents/kubernetes-handbook/node_modules/gitbook-plugin-prism/index.js:103:11)
    at Record.TemplateBlock.applyBlock (/Users/sadlar/.gitbook/versions/3.2.3/lib/models/templateBlock.js:205:23)
    at /Users/sadlar/.gitbook/versions/3.2.3/lib/output/getModifiers.js:56:33
    at /Users/sadlar/.gitbook/versions/3.2.3/lib/output/modifiers/highlightCode.js:47:24
    at /Users/sadlar/.gitbook/versions/3.2.3/lib/output/modifiers/editHTMLElement.js:11:16 code: 'MODULE_NOT_FOUND' }
error: error while generating page "practice/configuring-dns.md":

Error: read ETIMEDOUT 
```

**Comment by rootsongjc** [comment]
这个异常是可以忽略的，我编译的时候也会报这个错，这是因为prism的代码高亮里不支持Dockerfile导致的，虽然报错但是也可以成功编译。如果你无法成功编译的话，那么可以将所有markdown文件里指定的代码格式是`Dockerfile`的格式删除即可。

**Comment by johnson** [comment]
#268 修复了这个问题

**Comment by Xuzan9396** [comment]
怎么解决的啊

**Comment by rootsongjc** [comment]
将代码格式的配置 `Dockerfile`  修改为 `Docker` 即可。
