### ISSUE TITLE
Fluentd日志不能上送Elasticsearch

### ISSUE THREAD

**Issue by jason163** [rootsongjc/kubernetes-handbook#225]
## 环境

**版本和配置信息**

- kubernetes版本：1.9.1
- docker版本：Docker version 17.05.0-ce, build 89658be
- 网络插件：flannel
- 存储类型：

## 操作

**导致该问题的操作或现象**
按照搭建FEK步骤一步一步搭建，所有的组件都成功运行，Fluentd能够读取日志，但是不能上送在Elasticsearch集群，Fluentd&Elasticsearch都没有错误日志

## 日志
```bash
[root@k8s-master addons]# kubectl get pod -n kube-system
NAME                                   READY     STATUS    RESTARTS   AGE
elasticsearch-logging-v1-lk82l         1/1       Running   0          2h
elasticsearch-logging-v1-m5gjh         1/1       Running   0          2h
elasticsearch-logging-v1-svrss         1/1       Running   0          1h
fluentd-es-v1.22-dxfz9                 1/1       Running   0          2h
fluentd-es-v1.22-pg2kn                 1/1       Running   0          2h
heapster-75dfd64fd8-lnl25              1/1       Running   3          4h
kibana-logging-5cb6656fd7-wc48j        1/1       Running   7          22h
kube-dns-5c874ccb67-k6kz9              3/3       Running   71         8h
```

ElasticSearch日志

```bash
[root@k8s-master addons]# kubectl logs elasticsearch-logging-v1-lk82l -n kube-system
[2018-05-29 17:31:52,868][INFO ][node                     ] [elasticsearch-logging-v1-lk82l] version[2.4.1], pid[1], build[c67dc32/2016-09-27T18:57:55Z]
[2018-05-29 17:31:52,870][INFO ][node                     ] [elasticsearch-logging-v1-lk82l] initializing ...
[2018-05-29 17:31:55,179][INFO ][plugins                  ] [elasticsearch-logging-v1-lk82l] modules [reindex, lang-expression, lang-groovy], plugins [], sites []
[2018-05-29 17:31:55,287][INFO ][env                      ] [elasticsearch-logging-v1-lk82l] using [1] data paths, mounts [[/data (/dev/sda2)]], net usable_space [157.3gb], net total_space [167.9gb], spins? [possibly], types [xfs]
[2018-05-29 17:31:55,288][INFO ][env                      ] [elasticsearch-logging-v1-lk82l] heap size [1007.3mb], compressed ordinary object pointers [true]
[2018-05-29 17:32:04,062][INFO ][node                     ] [elasticsearch-logging-v1-lk82l] initialized
[2018-05-29 17:32:04,062][INFO ][node                     ] [elasticsearch-logging-v1-lk82l] starting ...
[2018-05-29 17:32:04,373][INFO ][transport                ] [elasticsearch-logging-v1-lk82l] publish_address {192.169.101.2:9300}, bound_addresses {0.0.0.0:9300}
[2018-05-29 17:32:04,435][INFO ][discovery                ] [elasticsearch-logging-v1-lk82l] kubernetes-logging/suo8K8KNRaS1Fjbur4nICA
[2018-05-29 17:32:07,695][INFO ][cluster.service          ] [elasticsearch-logging-v1-lk82l] new_master {elasticsearch-logging-v1-lk82l}{suo8K8KNRaS1Fjbur4nICA}{192.169.101.2}{192.169.101.2:9300}{master=true}, added {{elasticsearch-logging-v1-m5gjh}{wiGcJChaR22_Vl_Ckky7cQ}{192.169.2.2}{192.169.2.2:9300}{master=true},}, reason: zen-disco-join(elected_as_master, [1] joins received)
[2018-05-29 17:32:07,904][INFO ][http                     ] [elasticsearch-logging-v1-lk82l] publish_address {192.169.101.2:9200}, bound_addresses {0.0.0.0:9200}
[2018-05-29 17:32:07,905][INFO ][node                     ] [elasticsearch-logging-v1-lk82l] started
[2018-05-29 17:32:08,122][INFO ][gateway                  ] [elasticsearch-logging-v1-lk82l] recovered [0] indices into cluster_state
[2018-05-29 17:32:15,452][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [.kibana] creating index, cause [api], templates [], shards [1]/[1], mappings [config]
[2018-05-29 17:32:16,869][INFO ][cluster.routing.allocation] [elasticsearch-logging-v1-lk82l] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[.kibana][0]] ...]).
[2018-05-29 17:32:18,749][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] creating index, cause [auto(bulk api)], templates [], shards [5]/[1], mappings []
[2018-05-29 17:32:19,564][INFO ][cluster.routing.allocation] [elasticsearch-logging-v1-lk82l] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[logstash-2018.05.29][1], [logstash-2018.05.29][1]] ...]).
[2018-05-29 17:32:20,066][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] create_mapping [fluentd]
[2018-05-29 17:32:22,133][INFO ][cluster.routing.allocation] [elasticsearch-logging-v1-lk82l] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[logstash-2018.05.29][4]] ...]).
[2018-05-29 17:32:34,837][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:32:36,060][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:32:36,175][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:32:36,654][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:43:05,865][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:43:06,042][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:43:25,858][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:43:26,038][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [.kibana] create_mapping [index-pattern]
[2018-05-29 17:43:26,047][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:43:26,234][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [logstash-2018.05.29] update_mapping [fluentd]
[2018-05-29 17:43:34,985][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [.kibana] update_mapping [config]
[2018-05-29 17:43:40,344][INFO ][cluster.metadata         ] [elasticsearch-logging-v1-lk82l] [.kibana] create_mapping [search]
[2018-05-29 18:14:03,827][INFO ][cluster.service          ] [elasticsearch-logging-v1-lk82l] added {{elasticsearch-logging-v1-v6xnq}{b2SCIBSSS3ixWdsdYNd42g}{192.169.34.9}{192.169.34.9:9300}{master=true},}, reason: zen-disco-join(join from node[{elasticsearch-logging-v1-v6xnq}{b2SCIBSSS3ixWdsdYNd42g}{192.169.34.9}{192.169.34.9:9300}{master=true}])
[2018-05-29 18:14:05,257][INFO ][cluster.service          ] [elasticsearch-logging-v1-lk82l] added {{elasticsearch-logging-v1-9dmtg}{N6BqRGmySxeTCaUokjC7WA}{192.169.34.6}{192.169.34.6:9300}{master=true},}, reason: zen-disco-join(join from node[{elasticsearch-logging-v1-9dmtg}{N6BqRGmySxeTCaUokjC7WA}{192.169.34.6}{192.169.34.6:9300}{master=true}])
[2018-05-29 18:14:07,552][INFO ][cluster.service          ] [elasticsearch-logging-v1-lk82l] added {{elasticsearch-logging-v1-svrss}{WPTpbRwsQAuyocoT4x8cgw}{192.169.2.3}{192.169.2.3:9300}{master=true},}, reason: zen-disco-join(join from node[{elasticsearch-logging-v1-svrss}{WPTpbRwsQAuyocoT4x8cgw}{192.169.2.3}{192.169.2.3:9300}{master=true}])
[2018-05-29 19:59:00,660][INFO ][cluster.routing.allocation] [elasticsearch-logging-v1-lk82l] Cluster health status changed from [GREEN] to [YELLOW] (reason: [{elasticsearch-logging-v1-9dmtg}{N6BqRGmySxeTCaUokjC7WA}{192.169.34.6}{192.169.34.6:9300}{master=true} left]).
[2018-05-29 19:59:00,660][INFO ][cluster.service          ] [elasticsearch-logging-v1-lk82l] removed {{elasticsearch-logging-v1-9dmtg}{N6BqRGmySxeTCaUokjC7WA}{192.169.34.6}{192.169.34.6:9300}{master=true},}, reason: zen-disco-node-left({elasticsearch-logging-v1-9dmtg}{N6BqRGmySxeTCaUokjC7WA}{192.169.34.6}{192.169.34.6:9300}{master=true}), reason(left)
[2018-05-29 19:59:00,840][INFO ][cluster.routing          ] [elasticsearch-logging-v1-lk82l] delaying allocation for [2] unassigned shards, next check in [1m]
[2018-05-29 19:59:00,922][INFO ][cluster.routing.allocation] [elasticsearch-logging-v1-lk82l] Cluster health status changed from [YELLOW] to [RED] (reason: [{elasticsearch-logging-v1-v6xnq}{b2SCIBSSS3ixWdsdYNd42g}{192.169.34.9}{192.169.34.9:9300}{master=true} left]).
[2018-05-29 19:59:00,922][INFO ][cluster.service          ] [elasticsearch-logging-v1-lk82l] removed {{elasticsearch-logging-v1-v6xnq}{b2SCIBSSS3ixWdsdYNd42g}{192.169.34.9}{192.169.34.9:9300}{master=true},}, reason: zen-disco-node-left({elasticsearch-logging-v1-v6xnq}{b2SCIBSSS3ixWdsdYNd42g}{192.169.34.9}{192.169.34.9:9300}{master=true}), reason(left)
[2018-05-29 20:00:01,002][INFO ][cluster.routing          ] [elasticsearch-logging-v1-lk82l] delaying allocation for [1] unassigned shards, next check in [68.8ms]
```

Fluentd 日志 /var/log/fluentd.log

```bash
  2018-05-29 17:31:47 +0000 [warn]: suppressed same stacktrace
2018-05-29 17:31:49 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-29 17:31:53 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"elasticsearch-logging\", :port=>9200, :scheme=>\"http\"})!" plugin_id="object:3ff01839a7f4"
  2018-05-29 17:31:49 +0000 [warn]: suppressed same stacktrace
2018-05-29 17:31:54 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-29 17:32:01 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"elasticsearch-logging\", :port=>9200, :scheme=>\"http\"})!" plugin_id="object:3ff01839a7f4"
  2018-05-29 17:31:54 +0000 [warn]: suppressed same stacktrace
2018-05-29 17:32:01 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-29 17:32:18 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"elasticsearch-logging\", :port=>9200, :scheme=>\"http\"})!" plugin_id="object:3ff01839a7f4"
  2018-05-29 17:32:01 +0000 [warn]: suppressed same stacktrace
2018-05-29 17:32:19 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-29 17:32:48 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Can not reach Elasticsearch cluster ({:host=>\"elasticsearch-logging\", :port=>9200, :scheme=>\"http\"})!" plugin_id="object:3ff01839a7f4"
  2018-05-29 17:32:19 +0000 [warn]: suppressed same stacktrace
2018-05-29 17:32:49 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 17:32:49 +0000 [warn]: retry succeeded. plugin_id="object:3ff01839a7f4"
2018-05-29 18:14:32 +0000 [info]: following tail of /var/log/containers/elasticsearch-logging-v1-9dmtg_kube-system_elasticsearch-logging-4d928d3c2790817d5af7ad18819854321937efa0429734445310801cdc45a125.log
2018-05-29 18:14:32 +0000 [info]: following tail of /var/log/containers/elasticsearch-logging-v1-v6xnq_kube-system_elasticsearch-logging-8326278a3ef27b530f34b54c2ad834289002ab0226e5ba1a24d977f9a0c31b23.log
2018-05-29 19:59:16 +0000 [info]: detected rotation of /var/log/containers/elasticsearch-logging-v1-v6xnq_kube-system_elasticsearch-logging-8326278a3ef27b530f34b54c2ad834289002ab0226e5ba1a24d977f9a0c31b23.log; waiting 5 seconds
2018-05-29 19:59:16 +0000 [info]: detected rotation of /var/log/containers/elasticsearch-logging-v1-9dmtg_kube-system_elasticsearch-logging-4d928d3c2790817d5af7ad18819854321937efa0429734445310801cdc45a125.log; waiting 5 seconds
2018-05-29 19:59:50 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 19:59:52 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:00:23 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:00:27 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:00:38 +0000 [warn]: buffer flush took longer time than slow_flush_log_threshold: plugin_id="object:3ff01839a7f4" elapsed_time=77.757672101 slow_flush_log_threshold=20.0
2018-05-29 20:01:09 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:01:11 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:01:41 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:01:45 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:02:16 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-29 20:00:39 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Could not push logs to Elasticsearch after 2 retries. read timeout reached" plugin_id="object:3ff01839a7f4"
  2018-05-29 20:02:16 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:287:in `rescue in send'
  2018-05-29 20:02:16 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:277:in `send'
  2018-05-29 20:02:16 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.5.0/lib/fluent/plugin/out_elasticsearch.rb:271:in `write'
  2018-05-29 20:02:16 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:354:in `write_chunk'
  2018-05-29 20:02:16 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/buffer.rb:333:in `pop'
  2018-05-29 20:02:16 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:342:in `try_flush'
  2018-05-29 20:02:16 +0000 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.31/lib/fluent/output.rb:149:in `run'
2018-05-29 20:02:16 +0000 [warn]: retry succeeded. plugin_id="object:3ff01839a7f4"
2018-05-29 20:02:31 +0000 [warn]: retry succeeded. plugin_id="object:3ff01839a7f4"
2018-05-29 20:04:17 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:04:19 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:04:49 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:04:54 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:05:24 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-29 20:03:47 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Could not push logs to Elasticsearch after 2 retries. read timeout reached" plugin_id="object:3ff01839a7f4"
  2018-05-29 20:05:24 +0000 [warn]: suppressed same stacktrace
2018-05-29 20:05:24 +0000 [warn]: retry succeeded. plugin_id="object:3ff01839a7f4"
2018-05-29 20:05:55 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:05:57 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:06:27 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:06:31 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:07:01 +0000 [warn]: temporarily failed to flush the buffer. next_retry=2018-05-29 20:03:54 +0000 error_class="Fluent::ElasticsearchOutput::ConnectionFailure" error="Could not push logs to Elasticsearch after 2 retries. read timeout reached" plugin_id="object:3ff01839a7f4"
  2018-05-29 20:07:01 +0000 [warn]: suppressed same stacktrace
2018-05-29 20:07:32 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:07:34 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
2018-05-29 20:08:04 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 20:08:08 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
```

Kibana界面显示，已经有elasticsearch的索引模板，但是没有数据

![image](https://user-images.githubusercontent.com/3665287/40658320-7a3e345c-637d-11e8-9dfe-debe7024dd37.png)
![image](https://user-images.githubusercontent.com/3665287/40658328-86aaf8f6-637d-11e8-91f0-37c6662055d6.png)
Elasticsearch没有索引数据
![image](https://user-images.githubusercontent.com/3665287/40658377-a9e716c4-637d-11e8-9de5-808af9420036.png)

Node节点存在日志文件
![image](https://user-images.githubusercontent.com/3665287/40658471-fbd03722-637d-11e8-9255-786b7c14763d.png)

k8s链接文件也存在
![image](https://user-images.githubusercontent.com/3665287/40658499-0c8fd04a-637e-11e8-961e-153f67dc5f58.png)

大神，请指点哈，已经搞了一个星期了。感觉所有组件都运行成功，日志文件也收集到了，但上送到Elasticsearch无效。实在不知道什么原因了。。。

**日志或报错信息**

**Comment by jason163** [comment]
Fluentd日志 /var/log/fluentd.log一直处于这种状态，而且Elasticsearch仍然没有日志索引记录
[root@Linux-60-37 ~]# tail -f /var/log/fluentd.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/monitoring-grafana-654cc4d8b4-75q4m_kube-system_grafana-1868deb49cd83c1aeb5c540ac67c6879e786cfc64a3d1736c844691d5cf70067.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/my-nginx-9bbcf885d-p84f4_default_my-nginx-9db04d7e0d49a21e83edf0bbbf10d9247d9d5ce504a7cd6cb8e6fe8794d8945a.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/hostnames-79cfd57579-tw4qd_default_hostnames-3032ee1965c41b647173f87ea89ced05a6bedb33183d4457404ea37c11818c61.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/hostnames-79cfd57579-tbvsr_default_hostnames-390afcea1c89eb327e3fcc2829428f49dab6eaed5ac3e132e3a78f32a4ef6c10.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/monitoring-grafana-654cc4d8b4-75q4m_kube-system_grafana-6d71fe0ea9bea75c57763b556a592612dace86291b75c94d6231137809e46757.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/my-nginx-9bbcf885d-p84f4_default_my-nginx-50b58eb83aaa36185165379325c2603b5c9dc4d493f91f5a74da509bec85ad2f.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/kubernetes-dashboard-cc86d4596-2tdsq_kube-system_kubernetes-dashboard-66e85543257472662c06eaf044ef4a477c43b1836b0eed796e48377767b52603.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/hostnames-79cfd57579-tw4qd_default_hostnames-a3b3790b3beebe2b9a08a0528298a250fe73b6a5f34e856346e8ad78f0e98525.log
2018-05-29 20:26:41 +0000 [info]: following tail of /var/log/containers/fluentd-es-v1.22-62l6j_kube-system_fluentd-es-2c43be3e59dc9476195d5cb77cc7e861be8821f3bd086c2cf875d858be7dcc1f.log
2018-05-29 20:26:47 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}

**Comment by rootsongjc** [comment]
```
2018-05-29 19:59:50 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. read timeout reached
2018-05-29 19:59:52 +0000 [info]: Connection opened to Elasticsearch cluster => {:host=>"elasticsearch-logging", :port=>9200, :scheme=>"http"}
```
Fluentd是不是没有向正确的Elastic地址发送？

**Comment by jason163** [comment]
@rootsongjc 
Fluentd 如果没有正确的Elastic地址，Elastic的logstach-*索引有相应的模板，但是模板里没有值
![image](https://user-images.githubusercontent.com/3665287/40696467-92908246-63f8-11e8-81a9-2660f981f8cf.png)

版本内容，PS:大神能不能把Fluentd-elasticsearch:1.22 镜像上传到时速云上，让大家可以下载，不知道是不是版本问题导致
Fluentd: registry.cn-hangzhou.aliyuncs.com/google_images/fluentd-elasticsearch:1.22
Elastic: index.tenxcloud.com/jimmy/elasticsearch:v2.4.1-2

查看Fluentd日志 
[root@k8s-master addons]# kubectl logs fluentd-es-v1.22-4jdbl -n kube-system
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:3: warning: already initialized constant JSON::VERSION
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:3: warning: previous definition of VERSION was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:4: warning: already initialized constant JSON::VERSION_ARRAY
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:4: warning: previous definition of VERSION_ARRAY was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:5: warning: already initialized constant JSON::VERSION_MAJOR
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:5: warning: previous definition of VERSION_MAJOR was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:6: warning: already initialized constant JSON::VERSION_MINOR
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:6: warning: previous definition of VERSION_MINOR was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/version.rb:7: warning: already initialized constant JSON::VERSION_BUILD
/opt/td-agent/embedded/lib/ruby/2.1.0/json/version.rb:7: warning: previous definition of VERSION_BUILD was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:99: warning: already initialized constant JSON::NaN
/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:99: warning: previous definition of NaN was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:101: warning: already initialized constant JSON::Infinity
/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:101: warning: previous definition of Infinity was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:103: warning: already initialized constant JSON::MinusInfinity
/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:103: warning: previous definition of MinusInfinity was here
/opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.1/lib/json/common.rb:128: warning: already initialized constant JSON::UnparserError
/opt/td-agent/embedded/lib/ruby/2.1.0/json/common.rb:128: warning: previous definition of UnparserError was here

不知道是不是这么警告信息导致Fluentd无送向Elastic发送数据

**Comment by jason163** [comment]
我的因为是Elasticsearch没有生成索引数据，所有kibana虽然有索引模板但没有数据
